spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gram__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: ENC(vnorpyqN45UqERHLOINDYw==)
    password: ENC(b180A95E42O5V6nAlm3kig==)

server:
  port: 443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store-password: ENC(03hOH8jVndzwIWzzOtBEPw==)
    key-store: keystore.p12